### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by CGA1123** [CGA1123/slackerduty#1]
- [x] Add ability to acknowledge, escalate, resolve
- [ ] Add ability to add a note to incident 
- [ ] Add `/slackerduty incidents [ID]` command #4 
- [x] Add Honeycomb integration #2 
- [x] Add bugsnag integration #3 
- [x] Add ability to forward to a channel #3 
- [ ] Add ability to forward with a optional message #3 
- [ ] Docs / How-to install
- [ ] Better errors handling & feedback
- [x] Get rid of activesupport stuff
- [ ] Subscribe (Web?)
- [ ] Unsubscribe (Web?)
- [ ] Subscriptions (Web?)
- [ ] List Policies (Web?)
